### ISSUE TITLE
could not take a picture

### ISSUE THREAD

**Issue by oussamajebali** [frogermcs/InstaMaterial#12]
this is what i got when i'm trying to take a picture with my Galaxy S4

04-02 16:03:11.991  27490-27490/io.github.froger.instamaterial E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: io.github.froger.instamaterial, PID: 27490
    java.lang.RuntimeException: setParameters failed
            at android.hardware.Camera.native_setParameters(Native Method)
            at android.hardware.Camera.setParameters(Camera.java:1747)
            at com.commonsware.cwac.camera.CameraView.takePicture(CameraView.java:308)
            at com.commonsware.cwac.camera.CameraView.takePicture(CameraView.java:279)
            at io.github.froger.instamaterial.ui.activity.TakePhotoActivity.onTakePhotoClick(TakePhotoActivity.java:145)
            at io.github.froger.instamaterial.ui.activity.TakePhotoActivity$$ViewInjector$1.doClick(TakePhotoActivity$$ViewInjector.java:35)
            at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
            at android.view.View.performClick(View.java:4633)
            at android.view.View$PerformClick.run(View.java:19330)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by proman112111** [comment]
I do not know exactly the rootcause, but seem the class "MyCameraHost" is get something wrong implementation related to "previewSize". You can check it by remove the "getPictureSize" and "adjustPreviewParameters" function. Need more investigation.
