### ISSUE TITLE
Crash at Camera Preview 

### ISSUE THREAD

**Issue by masterravi** [frogermcs/InstaMaterial#27]
Hi ,
I am getting crash in TakePhotoActivity.

```
05-10 14:37:43.152 28423-28423/io.github.froger.instamaterial E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: io.github.froger.instamaterial, PID: 28423
                                                                                java.lang.RuntimeException: setParameters failed
                                                                                    at android.hardware.Camera.native_setParameters(Native Method)
                                                                                    at android.hardware.Camera.setParameters(Camera.java:2015)
                                                                                    at com.commonsware.cwac.camera.CameraView.takePicture(CameraView.java:308)
                                                                                    at com.commonsware.cwac.camera.CameraView.takePicture(CameraView.java:279)
                                                                                    at io.github.froger.instamaterial.ui.activity.TakePhotoActivity.onTakePhotoClick(TakePhotoActivity.java:155)
                                                                                    at io.github.froger.instamaterial.ui.activity.TakePhotoActivity$$ViewBinder$1.doClick(TakePhotoActivity$$ViewBinder.java:35)
                                                                                    at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                                    at android.view.View.performClick(View.java:4785)
                                                                                    at android.view.View$PerformClick.run(View.java:19884)
                                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

```

**Comment by uchar** [comment]
I have this problem too
